### ISSUE TITLE
format data finetune wav2vec

### ISSUE THREAD

**Issue by trongnk2106** [manhph2211/Vietnamese-Speech-Recognition#2]
cho mình hỏi là định dạng data để finetune wav2vec là gì ạ?
mình thấy bạn để train.json và test.json, nên mình không rõ format trong 2 file đó như thế nào?
mong bạn trả lời? Mình cảm ơn

**Comment by manhph2211** [comment]
Bạn có thể check file này ?
https://github.com/manhph2211/Vietnamese-Speech-Recognition/blob/main/data/custom.py
